[package]
name = "fp"
version = "0.1.3"
authors = ["Ilia Batii <batiyiv@gmail.com>"]
description = "Cairo Fixed Point Arithmetics for your smart-contracts"
license = "MIT-3.0"
repository = "https://github.com/carbonable-labs/carbon-protocol-v3"
keywords = ["starknet", "fixed point", "math", "division", "smart contracts"]
documentation = "https://github.com/baitcode/cairo-fixed-point-arithmetic"
readme = "README.md"
edition = "2024_07"

[dependencies]

[dev-dependencies]
cairo_test = "2.7.0"
